# Site settings
title: all Is Vanity
subtitle: all Is Vanity - chasing the wind
email: feedback@xenizogames.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 16537C #BLU
  secondary: E5691F #YEL
  secondary-dark: CFAF2A #OJ
  
# Footer settings
footer:
  copyright: Xenizo Games LLC
  location: Coming Soon
  social: Around The Web
  credits: Xenizo Games

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/XenizoGames
  - title: facebook
    url: https://www.facebook.com/xenizogames
  - title: google-plus
    url: https://plus.google.com/s/xenizogames
  - title: youtube 
    url: https://www.youtube.com/channel/UCjfIhbBokNbKjqZedNIIIzw

# Postal address (add as many lines as necessary)
address:
  - line: Early 2015
  
# Credits content
credits: 'All Is Vanity - Chasing The Wind is property of <a href="http://xenizogames.com">Xenizo Games LLC</a>.'

# Build settings
markdown: kramdown
permalink: pretty
